name: 'workflow-time'

inputs:
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false

outputs:
  result:
    value: ${{ steps.duration.outputs.result }}

runs:
  using: 'composite'
  steps:
    - name: workflow-time
      uses: actions/github-script@v6
      id: duration
      if: ${{ github.event_name != 'pull_request' }}
      with:
        github-token: ${{ github.event.inputs.github-token || inputs.github-token }}
        script: |
          const currentTime = new Date().getTime();
          const currentRun = await github.rest.actions.getWorkflowRun({
            owner: context.repo.owner,
            repo: context.repo.repo,
            run_id: context.runId
          });
          const startedAt = currentRun.data.run_started_at;
          const currentRunDurationInMillis = currentTime - new Date(startedAt).getTime();
          const currentRunDurationInSeconds = currentRunDurationInMillis / 1000;
          const currentRunDurationMinutesPart = Math.floor(currentRunDurationInSeconds / 60);
          const currentRunDurationSecondsPart = currentRunDurationInMillis % 60;

          const duration = "🕒 " + currentRunDurationMinutesPart + "m " + currentRunDurationSecondsPart + "s";
          return duration

        result-encoding: string
